import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const degrees = [
       {id: 1,
        firstName: 'Alpha Alpha Alpha Alpha AlphaAlpha',
        lastName: 'Bravo',
        degreeType: 'BS',
        university: 'Ghulam Ishaq Khan Institute',
        field: 'CS',
        gradYear: 2018,
        gpa: 3.5,
        fatherFirstName: 'Charlie',
        fatherLastName: 'Khan'
      },
      {id: 2,
        firstName: 'Sajeer',
        lastName: 'Khan',
        degreeType: 'BS',
        university: 'Ghulam Ishaq Khan Institute',
        field: 'EE',
        gradYear: 2019,
        gpa: 2.35,
        fatherFirstName: 'Saif',
        fatherLastName: 'Khan'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'NUST',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'NUST',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'IQRA',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'IQRA',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        university: 'IQRA',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        university: 'IQRA',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        university: 'IQRA',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        university: 'IQRA',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        university: 'IQRA',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        university: 'IQRA',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        university: 'IQRA',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'FAST',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        field: 'ME',
        university: 'FAST',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'BAHRIA',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'SZEBIST',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'IBA',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'LUMS',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'IBA',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
      {id: 3,
        firstName: 'Usman',
        lastName: 'Jameel',
        degreeType: 'MS',
        university: 'IQRA',
        field: 'ME',
        gradYear: 2021,
        gpa: 3.35,
        fatherFirstName: 'Gardezi',
        fatherLastName: 'Shafiq'
      },
    ];
    return {degrees};
  }
}
